# -*- coding: utf-8 -*-
"""0313week2 HW.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/116Xt2aTyqjB1iDhRCAnoCZEaet-dELR9
"""

#HELLO.PY
print("Hello World!")

import this

