# -*- coding: utf-8 -*-
"""0320week3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QRrL4TDkCUpFovKXzi0sS3iBQ2BJfbU0
"""

# input "03-19-2020"
# output "03-19-2020.csv"
#import requests
import pandas as pd

def get_covid_daily_data(input_date):
    csv_name = input_date + ".csv"
    github_url = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/{}".format(csv_name)
    #response = requests.get(github_url)
    df = pd.read_csv(github_url)
    # df.head()
    # df.tail()
    df.to_csv(csv_name, index=False)

user_input = input("Please input a date(mm-dd-yyyy):")
get_covid_daily_data(user_input)

from datetime import date, timedelta

start_date = date(2020, 1, 22)
#time_delta = timedelta(57)
#end_date = start_date + time_delta
date_period = [start_date + timedelta(i) for i in range(58)]
data_dates = [i.strftime('%m-%d-%Y') for i in date_period]
for dt in data_dates:
    print("Downloading {}.csv...".format(dt))
    get_covid_daily_data(dt)

#隨堂練習

movie_title="Avergers:endgames"
movie_rating=8.4
movie_length=184

print(movie_title)
print(movie_rating)
print(movie_length)

print(type(movie_title))
print(type(movie_length))
print(type(movie_rating))

