# -*- coding: utf-8 -*-
"""0327week4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v5Brj1Zul1MjxnkisHcyYzc4vAWS_1E9
"""

#隨堂練習
#(1)將目前的攝氏氣溫轉為華氏氣溫

celsius=28  #目前氣溫28度
fahrenheit=celsius*1.8+32

print(fahrenheit)

#華氏溫度回算攝氏溫度
#法一
fahrenheit=celsius*1.8+32
print(celsius)

#法二
celsius=(fahrenheit-32)*5/9
print(celsius)

#(2)俠客歐尼爾巔峰時期的 BMI 身體質量指數

shaq_height=2.16 #單位公尺
shaq_weight=147 #單位公斤

shaq_BMI=shaq_weight/(shaq_height**2)  
print(shaq_BMI)

#印出 I'm lovin' it!
#法一

a= 'I\'m lovin\' it!' #跳脫字元
print(a)
print(type(a))

#法二

a="I'm lovin' it!" #或用"""    """
print(a)
print(type(a))

#(3)輸出What did Ross say?

b="""Let's put aside the fact that you "accidentally" pick up my grandmother's ring."""
print(b)
print(type(b))

#(4)輸入城市名稱與天氣，並印出「我在OOO，天氣OOO」
#法一

today_city=input("請輸入所在城市:")
today_weather=input("請輸入目前天氣:")

print("我在{}，天氣{}".format(today_city,today_weather))  #印出不同物件的值 "{}".format(data)

#法二(但比較不建議)

today_city=input("請輸入所在城市:")
today_weather=input("請輸入目前天氣:")

print("我在"+today_city+",天氣"+today_weather)

#(5)身分證字號尾數是否為奇數

id_nail_number=5

id_nail_number%2==1

