# -*- coding: utf-8 -*-
"""0410week6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xGCxPlZIff6P5KT9WTwnNkHxyMmpUXY0
"""

#隨堂練習
#(1)月薪超過 4 萬或存款超過 50 萬就發信用卡

monthly_income = input("請輸入月薪：")
saving_account = input("請輸入存款：")

monthly_income=int(monthly_income)
saving_account=int(saving_account)

if (monthly_income>=40000 or saving_account>=500000):
  print("發信用卡")

#(2)判斷奇數偶數