# -*- coding: utf-8 -*-
"""0424week8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZhrtXiZvNAy2_WWygAM_h6Qerv4aIb4d
"""

player_hight=float(imput("請輸入球員身高(公尺):"))
player_weight=float(input("請輸入球員體重(公斤):"))
player_bmi=player_weight/player_hight**2
bmi_label=None
if player_bmi>30:
  bmi_label="obese"
elif player_bmi>25:
  bmi_label="over weight"
elif player_bmi

user_int = int(input("請輸入一個正整數："))
if user_int % 3==0 and user_int % 5==0:
  print("Fizz Buzz")
elif user_int % 3==0:
  print("Fizz")
elif user_int % 5==0:
  print("Buzz")

i=2 #start
while i <=20: #stop
  print(i)
  i += 2  #step  #可用visualize python來去跑跑看

i=1 
while i <=10: 
  print(i)
  i += 1
print("while loop is done.")

i=1
counter=1
while i<10:
  if i%2==0:
    counter+=1
  i+=1   #一定記得要縮排，不然i就會一直卡在4-5行
print(counter)

i=1
summation=0
while i <=100:
  summation += i
  i+=1
print(summation)

start_int = int(input("請輸入起始的正整數："))
stop_int = int(input("請輸入終止的正整數："))
i=start_int
while i<= stop_int:
  if i %2==1:
    print(i)
  i+=1

