# -*- coding: utf-8 -*-
"""0501week9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r5VW0Es4AQ9y_ChSt6_ExYde5P9kW0L9
"""

#迴圈基礎
x = int(input("請輸入起始的正整數："))
y = int(input("請輸入終止的正整數："))
i = x  #start
while i <= y:  #stop
  #test
  print(i)
  i+=1 #step

#隨堂練習
#(1)印出介於 x 到 y 之間的奇數（包含 x 與 y 假如它們是奇數）

x = int(input("請輸入起始的正整數："))
y = int(input("請輸入終止的正整數："))
i = x  #start
while i <= y:  #stop
  #test
  if i %2==1:
    print(i) #print跟著if函數
  i+=1 #step跟者while迴圈

#(2)承接上題，介於 x 到 y 之間的奇數有幾個（包含 x 與 y 假如它們是奇數）
x = int(input("請輸入起始的正整數："))
y = int(input("請輸入終止的正整數："))
odd_counter=0  #歸零
i = x  #start 
while i <= y: #stop
  if i%2 ==1:
    #odd_counter = odd_counter + 1
    odd_counter += 1  #跟著if函數
  i += 1  #跟著while迴圈 #step
print(odd_counter)

#(3)承接上題，介於 x 到 y 之間的奇數加總為何（包含 x 與 y 假如它們是奇數）
x = int(input("請輸入起始的正整數："))
y = int(input("請輸入終止的正整數："))
odd_summation=0  #歸零
i = x  #start 
while i <= y: #stop
  if i%2 ==1:
    #odd_summation = odd_summation + i
    odd_summation += i  #跟著if函數
  i += 1  #跟著while迴圈 #step
print("=========")
print(odd_summation)

#(4)判斷質數
x = int(input("請輸入起始的正整數："))
i =1  #start
divisor_counter=0  #歸零
while i<=x:        #stop
  if x % i==0:
    divisor_counter += 1
    print("{}可以被{}整除".format(x,i))
    print("因數個數目前有{}個".format(divisor_counter))
    print("======")
  i +=1 #step
print("anser")
print("{}共有{}個因數".format(x , divisor_counter))
if divisor_counter==2:
 print("{}不是質數".format(x))
else :
  print("{}不是質數".format(x))

#(5)Fizz-Buzz with while

i=1 #star
while i <=100 : #stop
  if i % 15==0:
    print("fizz buzz")
  elif i %3==0:
    print("fizz")
  elif i %5==0:
    print("buzz")
  else:
    print(i)
  i+=1 #step

