# -*- coding: utf-8 -*-
"""0508week10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1adUMlwRp188cuG9AgROj-7zAB7-vQMST
"""

lucky_num_0 = 7
lucky_num_1 = 24
lucky_num_2 = 5566
lucky_numbers = [7, 24, 5566]
sat = "Saturday"
sun = "Sunday"
weekend = ["Saturday", "Sunday"]
weekdays = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]

print(len(lucky_numbers))
print(len(weekend))
print(len(weekdays))

my_fav_weekday = "Friday"
print("My favorite weekday is {}.".format(my_fav_weekday))

print(lucky_numbers)
lucky_numbers.append(87)
print(lucky_numbers)

print(lucky_numbers)
lucky_numbers.pop()
print(lucky_numbers)

my_fav_group = lucky_numbers.pop()
print(lucky_numbers)
print(my_fav_group)

print(weekdays)
print(weekend)

weekdays + weekend
weekend + weekdays

print(weekdays[0])
print(weekdays[1])
print(weekdays[2])
print(weekdays[3])
print(weekdays[4])

i = 0
while i < 5:
    print(weekdays[i])
    i += 1

i = 0
while i < 2:
    print(weekend[i])
    i += 1

i = 0
while i < len(weekend):
    print(weekend[i])
    i += 1

i = 0
while i < len(weekdays):
    print(weekdays[i])
    i += 1

print(weekdays[-1])
print(weekdays[-2])
print(weekdays[-3])
print(weekdays[-4])
print(weekdays[-5])

#參考 cast 與 https://www.imdb.com/title/tt4154796 將飾演奇異博士（Doctor Strange）的演員用 indexing 方式選出來

cast = ['Robert Downey Jr.', 'Chris Evans', 'Mark Ruffalo', 'Chris Hemsworth', 'Scarlett Johansson', 'Jeremy Renner', 'Don Cheadle', 'Paul Rudd', 'Benedict Cumberbatch', 'Chadwick Boseman', 'Brie Larson', 'Tom Holland', 'Karen Gillan', 'Zoe Saldana', 'Evangeline Lilly']
#從開頭數
print(cast[8])

#從末端數
print(cast[-7])

#參考 cast 與 https://www.imdb.com/title/tt4154796 將第一集復仇者聯盟的六位英雄選出來
cast = ['Robert Downey Jr.', 'Chris Evans', 'Mark Ruffalo', 'Chris Hemsworth', 'Scarlett Johansson', 'Jeremy Renner', 'Don Cheadle', 'Paul Rudd', 'Benedict Cumberbatch', 'Chadwick Boseman', 'Brie Larson', 'Tom Holland', 'Karen Gillan', 'Zoe Saldana', 'Evangeline Lilly']
print(cast[:6])

#covid19
import pandas as pd

time_series_df = pd.read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")
cumulative_confirmed = list(time_series_df[time_series_df['Country/Region'] == 'Taiwan*'].values.ravel()[4:].astype(int))
cumulative_confirmed_lag = list(time_series_df[time_series_df['Country/Region'] == 'Taiwan*'].values.ravel()[4:].astype(int))
print(cumulative_confirmed)
print(cumulative_confirmed_lag)

print(len(cumulative_confirmed))
print(cumulative_confirmed[-1])

cumulative_confirmed_lag.insert(0, 0)
print(len(cumulative_confirmed_lag))
print(cumulative_confirmed_lag[0])

cumulative_confirmed_lag.pop()
print(len(cumulative_confirmed_lag))
print(cumulative_confirmed_lag[-1])



print(cumulative_confirmed)
print(cumulative_confirmed_lag)
#daily_incraese=?
daily_increase=[]
i = 0
while i <107:
   dayn_increase=cumulative_confirmed[i] - cumulative_confirmed_lag[i]
   print("Day{}:每日新增確診人數{}".format(i,dayn_increase)) 
   i+=1

