# -*- coding: utf-8 -*-
"""0522week12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xyun2pVboyoqAcCVIzlLtgIvYdW8Az6t
"""

x = int(input("請輸入一個正整數:"))
divisors = []
for i in range(1, x+1):
    if x % i == 0:
        divisors.append(i)
print(divisors)
n_divisors = len(divisors)
if n_divisors == 2:
    print("{}是質數".format(x))
else:
    print("{}不是質數".format(x))

x = int(input("請輸入一個正整數:"))
divisors = []
for i in range(1, x+1):
    if x % i == 0:
        divisors.append(i)
print(divisors)

# random 產生 1 個隨機數
import random

random.randint(1, 1000)
# random 產生 100 個隨機數
random_integers = []
for i in range(100):
    rand_int = random.randint(1, 1000)
    random_integers.append(rand_int)
print(random_integers)
print(len(random_integers))
# 找出第一大與第一小的數字
print(max(random_integers))
print(min(random_integers))
# 找出第二大與第二小的數字
rand_int_unique = set(random_integers)
rand_int_unique_list = list(rand_int_unique)
print(rand_int_unique_list)
rand_int_unique_list.sort()
print(rand_int_unique_list[1])  # second min
print(rand_int_unique_list[-2]) # secomd max

avengers = ["The Avengers", "Avengers: Age of Ultron", "Avengers: Infinity War", "Avengers: Endgame"]
for i, av in enumerate(avengers):
    print("第{}部上映的復仇者聯盟是:{}".format(i+1, av))

years = [2012, 2015, 2018, 2019]
for year, movie in zip(years, avengers):
    print("{}上映的年份是{}".format(movie, year))

