# -*- coding: utf-8 -*-
"""0629week13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17YKC6KC6r5q7H91PYLS5QjfIeFmA3KnV
"""

n_vowels = 0 
for i in 'azcbobobegghakl':
    if i in ['a', 'e', 'i', 'o', 'u']:       
       n_vowels += 1
print(n_vowels)

test_str = 'azcbobobegghak'
n_char = len(test_str)
n_bobs = 0
for i in range(n_char - 2):    
    if test_str[i:i+3] == 'bob':
        n_bobs += 1
print(n_bobs)

x = list(range(1, 101))
N = len(x)
x_bar = sum(x) / N
sse = 0
for xi in x:    
    squared_error = (xi - x_bar)**2
    sse += squared_error 
sample_mse = sse / (N-1)
sample_stdev = sample_mse**(0.5)
print(sample_stdev)

def absolute(x):
    """
    Returns the absolute value of x.
    """
    if x < 0:
        abs_x = -x
        print("{}的絕對值是{}".format(x, abs_x))
        return abs_x
    else:
        print("{}的絕對值是{}".format(x, x))
        return x
positive_56 = absolute(-5566)
print(positive_56)

def get_bmi(height, weight):
    """
    Calculate BMI based on height and weight
    """
    height = height / 100
    bmi = weight / height**2
    return bmi

get_bmi(216, 147)

def get_fahrenheit(x):
    """
    Transform a Celsius degree into  Farenheit scale
    """
    fah = x * 9/5 + 32
    return fah
get_fahrenheit(32)

